import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import ClaimTokens from './components/ClaimTokens';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
         Vesting Portal
        </h1>

        <div className={styles.grid}>
         <ClaimTokens/>
  
        </div>
      </main>

      
    </div>
  )
}
